# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmenu',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
